// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAF9FF1a_xMVcmy-Azvr4zr_UVgLqs3c',
    appId: '1:210086031226:web:74ff502abda19c01fdb0c3',
    messagingSenderId: '210086031226',
    projectId: 'sample-firebase-ai-app-9ba4d',
    authDomain: 'sample-firebase-ai-app-9ba4d.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-9ba4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXq-v_-71ufILCJcLZQUYoSjTfqZLq9IM',
    appId: '1:210086031226:android:a8126cdb851adfb0fdb0c3',
    messagingSenderId: '210086031226',
    projectId: 'sample-firebase-ai-app-9ba4d',
    storageBucket: 'sample-firebase-ai-app-9ba4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxOe5ubn4PZDdTMd1rTP_7YQ9P6RVTHQ',
    appId: '1:210086031226:ios:1517186eaf99138afdb0c3',
    messagingSenderId: '210086031226',
    projectId: 'sample-firebase-ai-app-9ba4d',
    storageBucket: 'sample-firebase-ai-app-9ba4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWxOe5ubn4PZDdTMd1rTP_7YQ9P6RVTHQ',
    appId: '1:210086031226:ios:1517186eaf99138afdb0c3',
    messagingSenderId: '210086031226',
    projectId: 'sample-firebase-ai-app-9ba4d',
    storageBucket: 'sample-firebase-ai-app-9ba4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM2wUbr2I1K3krwf1xAKRMBuKMWz0hvI8',
    appId: '1:210086031226:web:178a6f8f7e14a0f1fdb0c3',
    messagingSenderId: '210086031226',
    projectId: 'sample-firebase-ai-app-9ba4d',
    authDomain: 'sample-firebase-ai-app-9ba4d.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-9ba4d.firebasestorage.app',
  );
}
